### ISSUE TITLE
Custom configuration Dimensions / Foldernames?

### ISSUE THREAD

**Issue by renege** [punkave/symfony2-file-uploader-bundle#58]
Hi, how can I configure the folder and dimensions to my needs? These ones: 

```
  file_uploader.sizes:
    thumbnail:
      folder: thumbnails
      max_width: 80
      max_height: 80
```
